# Generated by Django 5.2.7 on 2025-11-08 02:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CountActApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PQRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('P', 'Petición'), ('Q', 'Queja'), ('R', 'Reclamo'), ('S', 'Sugerencia')], max_length=1)),
                ('asunto', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('ENVIADA', 'Enviada'), ('ASIGNADA', 'Asignada a Analista'), ('EN_PROCESO', 'En Proceso'), ('RESUELTA', 'Resuelta'), ('CERRADA', 'Cerrada')], default='ENVIADA', max_length=20)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='archivos_pqrs/')),
                ('analista_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pqrs_analizadas', to='CountActApp.analista')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pqrs_enviadas', to=settings.AUTH_USER_MODEL)),
                ('gestor_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pqrs_asignadas', to='CountActApp.gestor')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEstadoPQRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('fecha_cambio', models.DateTimeField(default=django.utils.timezone.now)),
                ('cambiado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pqrs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='CountActApp.pqrs')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaPQRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_respuesta', models.DateTimeField(default=django.utils.timezone.now)),
                ('archivo_reporte', models.FileField(blank=True, null=True, upload_to='reportes_analistas/')),
                ('enviada_al_cliente', models.BooleanField(default=False)),
                ('analista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CountActApp.analista')),
                ('pqrs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta', to='CountActApp.pqrs')),
            ],
        ),
    ]
