# Generated by Django 5.2.7 on 2025-11-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CountActApp', '0002_analista_gestor_pqrs_historialestadopqrs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('GESTOR', 'Gestor'), ('ANALISTA', 'Analista'), ('ADMINISTRADOR', 'Administrador')], default='CLIENTE', max_length=20),
        ),
    ]
