# Generated by Django 5.2.7 on 2025-11-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CountActApp', '0003_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('USUARIO', 'Usuario'), ('GESTOR', 'Gestor'), ('ANALISTA', 'Analista'), ('ADMINISTRADOR', 'Administrador')], default='USUARIO', max_length=20),
        ),
    ]
